### ISSUE TITLE
User requires Preference Manager role to be able to view Dispatcher

### ISSUE THREAD

**Issue by h3killa** [Chuckatron/CADvanced-beta#5]
**Describe the bug**
A user requires access to the Preference Manager role to be able to visibly see the dispatcher screen. If they do not have Preference Manager they receive a white screen.

**To Reproduce**
1. Set roles for a user to Player and Dispatcher
2. Have user view the dispatch screen
3. Ask user if they see white screen
4. User will say yes.
5. Pester user to get console log from web browser.
6. Assign user preference manager.
7. User can see dispatcher screen.

**Expected behavior**
Player only requires Player/Dispatcher to view dispatch screen

**Screenshots**
https://cdn.discordapp.com/attachments/553068112908386306/590571733556396051/unknown.png

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version N/A

**Additional context**
It appears this only occurs for the Preference Manager role.

**Comment by Chuckatron** [comment]
This is now fixed. Closing.
